apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: training-champ
images:
- name: asia.gcr.io/poc-innovation-iot/helloworld-champ
  newTag: 3d174313
