apiVersion: v1
kind: Service
metadata:
  name: helloworld-champ
  labels:
    app.kubernetes.io/name: helloworld-champ
    app.kubernetes.io/instance: helloworld-champ
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: helloworld-champ
    app.kubernetes.io/instance: helloworld-champ
